### ISSUE TITLE
"It did not work" Error 401

### ISSUE THREAD

**Issue by Isaacsh** [tumblr/pytumblr#103]
I just installed the module and guess successfully create app in tumblr website, but received an odd error calling `followers` method:

`client.info()`

{'user': {'blogs': [{'admin': True,
    'ask': False,
    'ask_anon': False,
    'ask_page_title': 'Ask me anything',
    'can_send_fan_mail': True,
    'can_subscribe': False,
    'description': '',
    'drafts': 0,
    'facebook': 'N',
    'facebook_opengraph_enabled': 'N',
    'followed': False,
    'followers': 0,
    'is_adult': False,
    'is_blocked_from_primary': False,
    'is_nsfw': False,
    'likes': 0,
    'messages': 0,
    'name': 'isaac2lord',
... 

`client.followers('cadillac.tumblr.com')`

{'errors': [{'detail': 'It did not work', 'title': 'Unauthorized'}],
 'meta': {'msg': 'Unauthorized', 'status': 401},
 'response': []}

'd appreciate any word of wisdom anyone can share.

**Comment by zcherries** [comment]
Blog owners can choose whether to show who they're following or not. I'm guessing it's because they aren't sharing that data, and therefore you can't see who they're following.

**Comment by Isaacsh** [comment]
Have tried on couple of other examples but none works. Am interested to see a single example that would work with .followers method.

**Comment by Isaacsh** [comment]
Thanks @jasonpenny, didn't know that. Do we have an endpoint that shows someone's else `followers` count/info, as in [GET followers/ids](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-followers-ids) in TW?

**Comment by jasonpenny** [comment]
Sorry, @Isaacsh I don't think there is an endpoint that shows that for blogs that you are not a member/owner of
