### ISSUE TITLE
TypeError: likes() takes 1 positional argument but 2 were given for .likes()

### ISSUE THREAD

**Issue by aauss** [tumblr/pytumblr#105]
Using _client.likes({'offset': 20, 'limit': 20})_ is giving me an error, that 2 positional arguments were given. I cannot figure how to change the limit of the returned likes. Furthermore, the returned amount of likes should be 20. Somehow for me it is two.

Thanks for you help in advance.

**Comment by aauss** [comment]
Thank you very much. I probably should have known better. 

Still, although I have over 6000 likes, executing this command in the interactive command line only returns two of my likes.

**Comment by wyfwyf112** [comment]
It seems the likes function only returns the latest 1000 likes.

**Comment by aauss** [comment]
It should, but for me it only returns the last two :(

**Comment by aauss** [comment]
> It should, but for me it only returns the last two :(

Works now. Thanks!
