### ISSUE TITLE
No param for adding url to local photo post

### ISSUE THREAD

**Issue by DrunkCodes** [tumblr/pytumblr#110]
I made a photo post on Tumblr and was able to add url to the photo post.

When I tried to do it with the api it wasn't possible. 

Please how can I get this done.

please can someone help

**Comment by jasonpenny** [comment]
You can use the `link` parameter,

for example to link to google:
```python
client.create_photo(blogName, state="published", tags=["testing", "ok"],
                    source="https://68.media.tumblr.com/b965fbb2e501610a29d80ffb6fb3e1ad/tumblr_n55vdeTse11rn1906o1_500.jpg",
                    link="https://www.google.com")

```
