### ISSUE TITLE
photoset post max upload photo is ten ?

### ISSUE THREAD

**Issue by 23233** [tumblr/pytumblr#113]
**i'm submit fourteen photo data** 
**but only show ten photo**
___ 

### this is show ten photo result:
![ten photo](https://user-images.githubusercontent.com/12870070/41606477-59a6090a-7416-11e8-824d-338d98031045.png)

### this is my code :

![tim 20180619230933](https://user-images.githubusercontent.com/12870070/41606513-6aeccaaa-7416-11e8-8a71-fc31f8238ea1.png)
![tim 20180619230952](https://user-images.githubusercontent.com/12870070/41606514-6c7cc690-7416-11e8-9498-988946115d44.png)

### i'm sure this submit photo number is fourteen , maybe  i want  
* **how show all photo**
* **how set photo size (one photo one row don't abreast)**

### thanks you I hope you can help me

___

**Comment by jasonpenny** [comment]
Yes, the maximum number of photos in a post is 10.

You can get all the photos to be full size on their own row with `photoset_layout`:

```python
self.client.create_photo(self.get_blog_name,
                         state="draft",
                         tags=tag_list,
                         format="markdown",
                         data=img_list,
                         caption=caption_str,
                         photoset_layout="1111111111")
```
