### ISSUE TITLE
What is the threshold for a new version/release?

### ISSUE THREAD

**Issue by nostalgebraist** [tumblr/pytumblr#142]
I recently submitted #141 and it was quickly merged to master by @kirooshu (thanks!).  However, it hasn't been released to PyPI, so the change will not affect most users.

Can I get some insight into when and why new releases will occur?  For example, is my change "enough" to justify a new v0.1.1 release, or will it take more changes to get there?

Context: I'm potentially interested in continuing to develop on pytumblr.  It's still incapable of some key things the API can do (like answering asks), and there is also room to grow the usability layer it provides over the raw API.

**Comment by skoobiii** [comment]
`&¿§`
