### ISSUE TITLE
Get keys for local application

### ISSUE THREAD

**Issue by heymingmo** [tumblr/pytumblr#170]
Hello!

I'm new to the Tumblr API (and using APIs in general). I'm hoping to work on a pet project application to pull metrics such as likes, follows, and post activity from my blog for general analytics purposes.
As this is intended to only run locally on my computer (I have no intention of having other people use it), I am having trouble getting keys as the registration process requires an application website which I do not have, is there another way I can get the necessary keys for my project, please?

Thank you in advance!

**Comment by dj-ratty** [comment]
It's simple if you check the [docs](https://www.tumblr.com/docs/en/api/v2#what-you-need).

> application website which I do not have

wdym? You can find URL for registering applications in [docs](https://www.tumblr.com/docs/en/api/v2#what-you-need) or [here](https://www.tumblr.com/oauth/apps). All you need is tumblr account

**Comment by heymingmo** [comment]
Ok it seems I confued myself...
Thank you for your reply!
