### ISSUE TITLE
May I know what need to input for the default callback in order to use this lib locally? 

### ISSUE THREAD

**Issue by arkilis** [tumblr/pytumblr#171]
<img width="499" alt="image" src="https://github.com/tumblr/pytumblr/assets/1528028/610fdb76-6bd9-4121-91f5-0002890cfd42">

**Thank you**

**Comment by sanmai** [comment]
Although I suspect you figured it out by now, I wanted to give you a heads up anyway: you can use any local URL such as `https://localhost/tumblr-callback`. You don't need a server there, but you must pick up the parameters and pass them to the library.
