### ISSUE TITLE
Oauth2 package dependency?

### ISSUE THREAD

**Issue by mkell43** [tumblr/pytumblr#42]
Hey guys and gals,

I'm starting to transition myself over to Python 3 and decided to play around with pytumblr as a part of that.

Unfortunately, it appears that oauth2 doesn't play nice with Python 3. [github issue](https://github.com/simplegeo/python-oauth2/issues/147)

Any plans on transitioning the package to using [oauthlib](https://github.com/idan/oauthlib)?  From what I'm reading it appears to be the new go to  package in Python for interacting with OAuth.

Even though EOL for Python 2 is [a ways off](http://hg.python.org/peps/rev/76d43e52d978), using oauthlib looks like it would allow someone who actually needs to use Python 3 and would like to use the pytumblr package, the ability to do so easily.

Thanks!

**Comment by jasonpenny** [comment]
pytumblr now relies on requests-oauthlib and oauthlib
