### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by codingjester** [tumblr/pytumblr#51]
We should try to support python3, it's 2.X eventually will be deprecated and we should do our best to make sure that we can support it going forward.

**Comment by gfleetwood** [comment]
Could someone detail what changes should be made so this can work in Python 3?

**Comment by Ivoz** [comment]
@gfleetwood for a start it needs to switch dependency away from the current old `oauth2` package, which only supports python 2.

**Comment by rbreu** [comment]
@gfleetwood: There's an open pull request for this: https://github.com/tumblr/pytumblr/pull/66

**Comment by davidtysman** [comment]
Hello,

pytumblr is not yet fully compatible with python3 : 
- Relative import into helpers.py
- urllib2 instead of the new modules
- ...

Using 2to3 makes it work.

Thks

**Comment by jabbalaci** [comment]
I made a fork and partially converted the project to Python 3: https://github.com/jabbalaci/pytumblr . With this version you can upload photos to Tumblr under Python 3. I didn't try the other functionalities since I only needed the photo support.

**Comment by jasonpenny** [comment]
pytumblr now supports python3
