### ISSUE TITLE
Inconsistent boolean GET parameters

### ISSUE THREAD

**Issue by thachhoang** [tumblr/pytumblr#56]
From https://api.tumblr.com/console/calls/blog/posts, to include reblog info in each post I can do this:

``` python
client.posts('staff.tumblr.com', reblog_info=True)
```

In practice I have to do this:

``` python
client.posts('staff.tumblr.com', reblog_info='true')
```

because pytumblr adds uppercase boolean values as GET parameters ('True'), which the Tumblr API ignores.

**Comment by jasonpenny** [comment]
This no longer seems to be a problem, both `True` and `'true'` are including the reblog info
