### ISSUE TITLE
Error when Creating photo post

### ISSUE THREAD

**Issue by ydaniels** [tumblr/pytumblr#61]
Anytime I try uploading an image I keep getting {"meta":{"status":401,"msg":"Not
Authorized"},"response":[]}. with unicode string as the blog name

**Comment by LolWalid** [comment]
Did you fix the problem ? I'm getting the same issue when uploading local files.

The source parameters works fine.

```python
client.create_photo(blog_name, state = "published", data="path/to/my/file", caption="doesn't work")

client.create_photo(blog_name, state = "published", source="http://url/to/my/file", caption="work")
```
