### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by mika7700** [tumblr/pytumblr#75]
hello
sorry i'm french
i can not run
I have an error on the test
I have my tumblr key, but I do not understand all

EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
======================================================================
ERROR: test_blogInfo (__main__.TumblrRestClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/pytumblr/pytumblr-master/tests/test_pytumblr.py", line 16, in setUp
    with open('tests/tumblr_credentials.json', 'r') as f:
IOError: [Errno 2] No such file or directory: 'tests/tumblr_credentials.json'

=========--------------------------------------------------
Ran 33 tests in 0.335s

FAILED (errors=33)
>>>

**Comment by codingjester** [comment]
It cannot open that file, in that path. So something is wrong with how you are actually running the tests. Can you give more examples on how you're actually running the test? Invocation and current path will be helpful.

**Comment by mika7700** [comment]
hello
i started the  run by f5

[code]Traceback (most recent call last):
  File "/home/pi/Desktop/pytumblr-master/tests/test_pytumblr.py", line 16, in setUp
    with open('tests/tumblr_credentials.json', 'r') as f:
IOError: [Errno 2] No such file or directory: 'tests/tumblr_credentials.json'

----------------------------------------------------------------------
Ran 32 tests in 0.287s

FAILED (errors=32)
>>> [code]


my file is here
 /home/pi/Desktop/pytumblr-master/tests

thanks for your help

**Comment by mika7700** [comment]
Hello
I can post on tumblr but how to change the "# below gif" ?

**Comment by mika7700** [comment]
Hello
I can post on tumblr but how to change the "# below gif" ?

**Comment by ceyko** [comment]
@mika7700 Do you mean tags? You can add `tags` into the call you're making. For example:

```
client.create_text("yourblogname", tags=["tag1", "tag2"], ...)
```

**Comment by mika7700** [comment]
thank you so much
I found the line edit
