### ISSUE TITLE
ImportError: No module named 'helpers'

### ISSUE THREAD

**Issue by lynncyrin** [tumblr/pytumblr#77]
Is fixed by [the Python 3 support pull request](https://github.com/tumblr/pytumblr/pull/66)

Which, pending it being merged into master, you can install with

```
pip install git+git://github.com/dianakhuang/pytumblr.git@diana/python-3-support
```

Hopefully this will save someone 5 minutes

**Comment by Ph0enix0** [comment]
You can also change `from helpers import blahblah' to 'from pytumblr.helpers import blahblah'

**Comment by romsson** [comment]
Alternatively 
`pip install https://github.com/dianakhuang/pytumblr/archive/diana/python-3-support.zip`

**Comment by jerusalemprogrammer** [comment]
None of these suggested solutions worked for me.

**Comment by boisei0** [comment]
@jerusalemprogrammer The error you get suggests you are still using the default pytumblr branch. Make sure you use the pip from your development environment and not the system pip. I successfully installed it on Python 3.6.1 last week using the python-3-support branch mentioned in the comments above.

**Comment by jerusalemprogrammer** [comment]
I don't know what you mean by default pytumblr branch...

I went to Tumblr API and found the Python that pointed me to the following:
https://github.com/tumblr/pytumblr

I then tried to execute the code to begin connecting to Tumblr API, but
received errors and then googled those errors and landed to this page:
https://github.com/tumblr/pytumblr/issues/77

I pip installed within my virtual environment and not my system python pip.

The suggested solutions didn't work.

JerusalemProgrammer.com
JerusalemProgrammers.com
JerusalemProgramming.com

**Comment by Jay-Dai** [comment]
Experienced the same problem as jerusalemprogrammer.

I tried the solutions proposed by :
lynnco
Ph0enix0
romsson
I don t really understand boisei0 solution so didn t try it

lynnco & romsson solutions displays the same error

Ph0enix0 solution display a new error : 
ImportError: No module named 'request'
If I apply the same correction again to 'request' it displays :
"  File "C:\Python\lib\site-packages\pytumblr\request.py", line 37
    except RedirectLimit, e:
                        ^
SyntaxError: invalid syntax"

I m not sure, but it looks like this is a Python 3/Python 2 syntax difference that creates the problem right ? I m using python 3.5.3

**Comment by Ph0enix0** [comment]
@Jay-Dai, yes, change the line to `except RedirectLimit as e:` if you want to fix this issue. Though, it is likely there are many more syntax errors.
I would suggest @romsson 's solution as it would correct all translation issues. Remove the Python 2 version of pytumblr and use the python3 3rd party version.

**Comment by sinapil** [comment]
This solved my solution in a second!

`pip3 install blinkpy==0.5.2`

**Comment by sinapil** [comment]
This solved my problem in a second:

`pip3 install blinkpy==0.5.2`

**Comment by BerenLuthien** [comment]
I have same problem on Python **2.7**
Any solution ? Thanks

**Comment by joshuasturre** [comment]
I fixed this problem on my Mac by first running 
```
pip unistall pytumblr
```

and then running
```
pip install https://github.com/dianakhuang/pytumblr/archive/diana/python-3-support.zip
```

**Comment by jasonpenny** [comment]
With the recent changes merged, this should no longer be an issue

**Comment by royrogers** [comment]
https://github.com/menkrep1337/XSSCon/issues/3#issuecomment-536294687

/opt# git clone https://github.com/menkrep1337/XSSCon.git

/opt# cd XSSCon/

/opt/XSSCon# pip3 install -r requirements.txt

/opt/XSSCon# pip install https://github.com/dianakhuang/pytumblr/archive/diana/python-3-support.zip

/opt/XSSCon# pip3 install helpers

/opt/XSSCon# nano /opt/XSSCon/helper.py

-- coding: utf-8 --

/opt/XSSCon# pip3 install pytumblr

/opt/XSSCon# nano xsscon.py

import pytumblr.helpers

/opt/XSSCon# python3 xsscon.py
