### ISSUE TITLE
authorization failing for OAuth GET functions after successful POST call

### ISSUE THREAD

**Issue by version-one** [tumblr/pytumblr#87]
after calling a function that uses POST, for example `client.like(...)` or `client.create_text(...)`, the next call to a 'GET' function requiring OAuth authorization fails with a 401 error (calling GET functions that require an API key work fine however).

for example after the POST function `client.create_text(...)`, a call to the GET function` client.likes(...)` will fail, although a call to the GET function `client.posts(...)` will work fine. `client.likes(...)` requires OAuth whereas `client.posts(...)` requires an API key -- according to the [tumblr API documentation](https://www.tumblr.com/docs/en/api/v2/).

don't know if this is an issue with pytumblr, the oauth library, or the tumblr API itself. a workaround is to reinitialize the client before every call with: `client = pytumblr.TumblrRestClient(...)`

**Comment by jasonpenny** [comment]
I can't reproduce this, @version-one can you give a code example that demonstrates the problem?
