### ISSUE TITLE
blog/{blog-identifier}/following API

### ISSUE THREAD

**Issue by brondavies** [tumblr/pytumblr#90]
I am trying to use this api:
https://www.tumblr.com/docs/en/api/v2#blog-following
but It seems as though it is not implemented in pytumblr so I wrote this

```
        url = '/v2/blog/%s/following/' % blog_name
        response = get_client().send_api_request("get", url, values, ["limit", "offset"])
```

however, I always get a 404 error.  Is the documentation missing something?

**Comment by finalion** [comment]
Exactly. Maybe this interface has been removed.
